import type { Metadata } from "next";
// import localFont from "next/font/local";
// import { Inter,Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// const outfitNormal = Outfit({
//   subsets: ["latin"],
//   variable: "--font-outfit",
//   weight: ["400", "700"],
//   style: "normal",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
      >
        {children}
        {/* {`${geistSans.variable} ${geistMono.variable} antialiased`} */}
      </body>
    </html>
    </ClerkProvider>
  );
}
